apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-app
  namespace: cv-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cv.kravix.ch
      secretName: cv-app-tls
  rules:
    - host: cv.kravix.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-app
                port:
                  name: http